language: go

go:
  - 1.8

services:
  - docker

before_script:
  - CGO_ENABLED=0 go get -v gopkg.in/bblfsh/sdk.v1/...
  - bblfsh-sdk prepare-build .
  - go get -v -t ./...

script:
  - make test integration-test

after_success:
  - make push
