sdk: '2'
go-runtime:
  version: '1.12-alpine'
native:
  image: 'php:7-alpine3.6'
  static:
    - path: 'ast'
      dest: 'native'
    - path: 'src'
      dest: 'src'
  build:
    add:
      - path: 'https://getcomposer.org/installer'
        dest: '/tmp/composer-setup.php'
    deps:
      - 'php /tmp/composer-setup.php --install-dir=/bin/'
    run:
      - 'composer.phar install'
    artifacts:
      - path: '/native/vendor'
        dest: 'vendor'
  test:
    run:
      - './vendor/bin/phpunit tests/'